### ISSUE TITLE
fail with AMD Ryzen 7 5700G Processor with Radeon Graphics  Vega 8 graphics. with fedora linux

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [jaswon/osu-dreamer#12]
```
python scripts/cli.py fit -c config.yml -c osu_dreamer/model/model.yml --data.src_path lazerexport 
/home/krafi.info/.local/lib/python3.11/site-packages/lightning_fabric/utilities/seed.py:40: No seed found, seed set to 2989082511
Seed set to 2989082511
/home/krafi.info/.local/lib/python3.11/site-packages/lightning_fabric/connector.py:565: `precision=16` is supported for historical reasons but its usage is discouraged. Please set your precision to 16-mixed instead!
Traceback (most recent call last):
  File "/home/krafi.info/Games/osu-dreamer/scripts/cli.py", line 7, in <module>
    cli = LightningCLI(Model, Data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krafi.info/.local/lib/python3.11/site-packages/pytorch_lightning/cli.py", line 383, in __init__
    self.instantiate_classes()
  File "/home/krafi.info/.local/lib/python3.11/site-packages/pytorch_lightning/cli.py", line 537, in instantiate_classes
    self.trainer = self.instantiate_trainer()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krafi.info/.local/lib/python3.11/site-packages/pytorch_lightning/cli.py", line 548, in instantiate_trainer
    return self._instantiate_trainer(trainer_config, extra_callbacks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krafi.info/.local/lib/python3.11/site-packages/pytorch_lightning/cli.py", line 573, in _instantiate_trainer
    return self.trainer_class(**config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krafi.info/.local/lib/python3.11/site-packages/pytorch_lightning/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/krafi.info/.local/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 402, in __init__
    self._accelerator_connector = _AcceleratorConnector(
                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krafi.info/.local/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 152, in __init__
    self._accelerator_flag = self._choose_gpu_accelerator_backend()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krafi.info/.local/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 372, in _choose_gpu_accelerator_backend
    raise MisconfigurationException("No supported gpu backend found!")
lightning_fabric.utilities.exceptions.MisconfigurationException: No supported gpu backend found!

```

i am using AMD Ryzen 7 5700G Processor with Radeon Graphics Vega 8 graphics. with fedora linux

**Comment by krafi-code** [comment]
lspci
30:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] (rev c8)

**Comment by krafi-code** [comment]
please help me how can i set my gpu vega 8

from pytorch_lightning.cli import LightningCLI
from osu_dreamer.model import Model
from osu_dreamer.data import Data

if __name__ == "__main__":
    cli = LightningCLI(Model, Data, fast_dev_run=True, gpus=0)

**maybe i need to modify something like this ?** 

it not work
